### ISSUE TITLE
IndexError: list index out of range error on a color image

### ISSUE THREAD

**Issue by liudechris** [thumbor/thumbor#785]
### Original image

https://d38eepresuu519.cloudfront.net/cdd9c5f1a59048df983c33844694dd46/original.jpg
### Cropped image returns 500 error

https://d3rq5c7ii2flus.cloudfront.net/nn9t0bY4FWQNkDpaF44eCyRBWO0=/500x0/https://d38eepresuu519.cloudfront.net/cdd9c5f1a59048df983c33844694dd46/original.jpg
### Operating system

Ubuntu 14.04.3 LTS
Thumbor 3.15.0
Tornado 3.1.1
### Traceback

  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1115, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/thumbor/loaders/http_loader.py", line 49, in return_contents
    callback(response.body)
  File "/usr/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 298, in handle_loader_loaded
    buffer = engine.read()
  File "/usr/lib/python2.7/dist-packages/thumbor/engines/pil.py", line 137, in read
    self.image.save(img_buffer, FORMATS[ext], **options)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1468, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 495, in _save
    subsampling = get_sampling(im)
  File "/usr/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 451, in get_sampling
    sampling = im.layer[0][1:3] + im.layer[1][1:3] + im.layer[2][1:3]
IndexError: list index out of range

I noticed issues #255 and #236 point to the same error, but in this case the image is not monochromatic.

Thanks for your help.

**Comment by guilhermef** [comment]
This error doesn't happen on newer versions http://thumbor.thumborize.me/unsafe/d38eepresuu519.cloudfront.net/cdd9c5f1a59048df983c33844694dd46/original.jpg

**Comment by liudechris** [comment]
@guilhermef Thanks. I installed Thumbor (v6) using pip on Ubuntu 14.04 but there's some issues with OpenCV.

###Traceback
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==6.0.1', 'console_scripts', 'thumbor')()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 124, in main
    importer = get_importer(config)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 58, in get_importer
    importer.import_modules()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 51, in import_modules
    self.import_item('ENGINE', 'Engine')
  File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 95, in import_item
    module = self.import_class('%s.%s' % (conf_value, class_name))
  File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 43, in import_class
    return import_class(name, get_module)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 19, in import_class
    module = get_module and __import__(name) or __import__(module_name)
ImportError: No module named opencv

**Comment by rfloriano** [comment]
@liudechris seems that OpenCV just uninstalled.
Do you have executed the [alternative installation](http://thumbor.readthedocs.io/en/latest/installing.html#alternative-installation)?
The "python-opencv" package should solve it.

**Comment by liudechris** [comment]
@rfloriano Thanks for the suggestion. I tried the alternative installation (with --upgrade --force-reinstall) but there's still an issue. I installed ffmpeg on Ubuntu 14.04 using this [http://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/](link).

**Comment by vanbinh91** [comment]
[root@connect360 bin]# thumbor
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==6.3.2', 'console_scripts', 'thumbor')()
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/server.py", line                                                                124, in main
    importer = get_importer(config)
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/server.py", line                                                                58, in get_importer
    importer.import_modules()
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/importer.py", lin                                                               e 51, in import_modules
    self.import_item('ENGINE', 'Engine')
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/importer.py", lin                                                               e 95, in import_item
    module = self.import_class('%s.%s' % (conf_value, class_name))
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/importer.py", lin                                                               e 43, in import_class
    return import_class(name, get_module)
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/importer.py", lin                                                               e 19, in import_class
    module = get_module and __import__(name) or __import__(module_name)
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/engines/__init__.                                                               py", line 12, in <module>
    from xml.etree.ElementTree import ParseError
ImportError: cannot import name ParseError

Why thumbor not working? Pls help me!!!!!!!!!!!!!!!!!

**Comment by heynemann** [comment]
Any luck fixing this? As this was a while back I'm closing it.

If you have any further questions on this issue, please reopen it.
